export const MOCK_MENU = [
  { id: 1, name: 'ข้าวผัดหมู', category: 'food', price: 45 },
  { id: 2, name: 'ข้าวผัดไก่', category: 'food', price: 45 },
  { id: 3, name: 'ผัดกะเพราหมู', category: 'food', price: 50 },
  { id: 4, name: 'ผัดกะเพราไก่', category: 'food', price: 50 },
  { id: 5, name: 'ผัดพริกแกงหมู', category: 'food', price: 55 },
  { id: 6, name: 'ผัดพริกแกงไก่', category: 'food', price: 55 },
  { id: 7, name: 'ผัดซีอิ๊วหมู', category: 'food', price: 50 },
  { id: 8, name: 'ผัดซีอิ๊วไก่', category: 'food', price: 50 },
  { id: 9, name: 'ข้าวหมูทอดกระเทียม', category: 'food', price: 55 },
  { id: 10, name: 'ข้าวไข่เจียว', category: 'food', price: 40 },
  { id: 11, name: 'ข้าวไข่เจียวหมูสับ', category: 'food', price: 45 },
  { id: 12, name: 'ข้าวคะน้าหมูกรอบ', category: 'food', price: 60 },

  { id: 13, name: 'น้ำเปล่า', category: 'drink', price: 10 },
  { id: 14, name: 'โค้ก', category: 'drink', price: 20 },
  { id: 15, name: 'เป๊ปซี่', category: 'drink', price: 20 },
  { id: 16, name: 'แฟนต้าน้ำส้ม', category: 'drink', price: 20 },
  { id: 17, name: 'ชาเย็น', category: 'drink', price: 25 },
  { id: 18, name: 'กาแฟเย็น', category: 'drink', price: 30 },
  { id: 19, name: 'โอเลี้ยง', category: 'drink', price: 20 },
  { id: 20, name: 'น้ำเขียว', category: 'drink', price: 20 },
];
