module.exports = [
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/app/(customer)/tables/[tableId]/menu/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/(customer)/tables/[tableId]/menu/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/components/menu/Menu.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/components/menu/Menu.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/menu/Menu.tsx <module evaluation>", "default");
}),
"[project]/components/menu/Menu.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/components/menu/Menu.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/menu/Menu.tsx", "default");
}),
"[project]/components/menu/Menu.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$menu$2f$Menu$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/components/menu/Menu.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$menu$2f$Menu$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/components/menu/Menu.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$menu$2f$Menu$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/mock-data/menu.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "MOCK_MENU",
    ()=>MOCK_MENU
]);
const MOCK_MENU = [
    {
        id: 1,
        name: 'ข้าวผัดหมู',
        category: 'food',
        price: 45
    },
    {
        id: 2,
        name: 'ข้าวผัดไก่',
        category: 'food',
        price: 45
    },
    {
        id: 3,
        name: 'ผัดกะเพราหมู',
        category: 'food',
        price: 50
    },
    {
        id: 4,
        name: 'ผัดกะเพราไก่',
        category: 'food',
        price: 50
    },
    {
        id: 5,
        name: 'ผัดพริกแกงหมู',
        category: 'food',
        price: 55
    },
    {
        id: 6,
        name: 'ผัดพริกแกงไก่',
        category: 'food',
        price: 55
    },
    {
        id: 7,
        name: 'ผัดซีอิ๊วหมู',
        category: 'food',
        price: 50
    },
    {
        id: 8,
        name: 'ผัดซีอิ๊วไก่',
        category: 'food',
        price: 50
    },
    {
        id: 9,
        name: 'ข้าวหมูทอดกระเทียม',
        category: 'food',
        price: 55
    },
    {
        id: 10,
        name: 'ข้าวไข่เจียว',
        category: 'food',
        price: 40
    },
    {
        id: 11,
        name: 'ข้าวไข่เจียวหมูสับ',
        category: 'food',
        price: 45
    },
    {
        id: 12,
        name: 'ข้าวคะน้าหมูกรอบ',
        category: 'food',
        price: 60
    },
    {
        id: 13,
        name: 'น้ำเปล่า',
        category: 'drink',
        price: 10
    },
    {
        id: 14,
        name: 'โค้ก',
        category: 'drink',
        price: 20
    },
    {
        id: 15,
        name: 'เป๊ปซี่',
        category: 'drink',
        price: 20
    },
    {
        id: 16,
        name: 'แฟนต้าน้ำส้ม',
        category: 'drink',
        price: 20
    },
    {
        id: 17,
        name: 'ชาเย็น',
        category: 'drink',
        price: 25
    },
    {
        id: 18,
        name: 'กาแฟเย็น',
        category: 'drink',
        price: 30
    },
    {
        id: 19,
        name: 'โอเลี้ยง',
        category: 'drink',
        price: 20
    },
    {
        id: 20,
        name: 'น้ำเขียว',
        category: 'drink',
        price: 20
    }
];
}),
"[project]/app/(customer)/tables/[tableId]/menu/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$menu$2f$Menu$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/components/menu/Menu.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$mock$2d$data$2f$menu$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/mock-data/menu.ts [app-rsc] (ecmascript)");
;
;
;
const page = async ({ params })=>{
    const { tableId } = await params;
    const menu = __TURBOPACK__imported__module__$5b$project$5d2f$mock$2d$data$2f$menu$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["MOCK_MENU"];
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$menu$2f$Menu$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
            tableId: tableId,
            menus: menu
        }, void 0, false, {
            fileName: "[project]/app/(customer)/tables/[tableId]/menu/page.tsx",
            lineNumber: 9,
            columnNumber: 7
        }, ("TURBOPACK compile-time value", void 0))
    }, void 0, false, {
        fileName: "[project]/app/(customer)/tables/[tableId]/menu/page.tsx",
        lineNumber: 8,
        columnNumber: 5
    }, ("TURBOPACK compile-time value", void 0));
};
const __TURBOPACK__default__export__ = page;
}),
"[project]/app/(customer)/tables/[tableId]/menu/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/(customer)/tables/[tableId]/menu/page.tsx [app-rsc] (ecmascript)"));
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__7e62196b._.js.map